### PR TITLE
tkaiser2-2

### PR DESCRIPTION
**Pull request by timkphd**
Changes for new modules, minor chance to Linaro pages and added ddt section to Linaro

### CODE REVIEW

**Comment by yandthj** [comment]
I think this needs to be changed to have the base branch be gh-pages, instead of master

**Comment by timkphd** [comment]
The gh-pages branch has source code references to the master branch.  I made minor changes to those files for new modules.

**Comment by yandthj** [comment]
I saw the PR for the master branch changes and merged that in already. This PR is to merge the gh-pages branch into master, which doesn't seem right. I think it needs to be changed to be merging your gh-pages branch into this repo's gh-pages branch

**Comment by yandthj** [comment]
Superseded by PR #700

**Pull request closed without merging**
