### PR TITLE
Update docs for gams, lammps, gaussian, qchem, fenics

### PR DESCRIPTION
**Pull request by sinolonghai**
All are updated.

Hai Long

### CODE REVIEW

**Review by claralarson — COMMENTED** [review]
In lines 45 and 49 of gams.md, do [1] and [2] render nicely in github pages or does this need to be changed to look nicer?

**Review by claralarson — COMMENTED** [review]
I think there are some issues with the ``` at the top of gaussian.md for creating a cell that provides the message that you have to agree to in order to use gaussian

**Review by claralarson — COMMENTED** [review]
Line 111 in gaussian.md links to other documentation for gaussian on GPUs, should some of that documentation be pulled into gaussian.md?

**Review by claralarson — COMMENTED** [review]
can the sample script for lammps be run on both eagle and swift? If so, might be good to make that clear in the submission script section

**Review by claralarson — CHANGES_REQUESTED** [review]
I made a few comments regarding format. Content looks good

**Review by yandthj — APPROVED** [review]

**Pull request merged**
